name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: BuildApp
      run: go build -v ./cmd/gkbm

    - name: BuildDeploy
      run: go build -v ./cmd/deploy

    - name: Test
      run: go test -v ./cmd/gkbm

    - uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: ./deploy
      
    - uses: actions/upload-artifact@v2
      with:
        name: gkbm
        path: ./gkbm  
